name: CI/CD Secure Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t devsecure-api:latest .

#      - name: Install Trivy
#        run: docker run aquasec/trivy

      - name: Scan Docker image with Trivy (via Docker)
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v ${{ github.workspace }}:/project \
            aquasec/trivy image devsecure-api:latest
      

      - name: Install GitLeaks
        run: |
          curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest \
            | grep "browser_download_url.*linux_x64.tar.gz" \
            | cut -d : -f 2,3 \
            | tr -d \" \
            | wget -qi -
          tar -xvzf gitleaks*.tar.gz
          sudo mv gitleaks /usr/local/bin/

      - name: Run GitLeaks scan
        run: gitleaks detect --source . --report-format sarif --report-path gitleaks.sarif

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Snyk and authenticate
        run: |
          npm install -g snyk
          snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk test
        run: snyk test --file=requirements.txt --package-manager=pip

      - name: Scan Docker image with Snyk
        run: snyk container test devsecure-api:latest

      - name: Push Docker image
        run: docker tag devsecure-api:latest ${{ secrets.DOCKER_USERNAME }}/devsecure-api:latest && docker push ${{ secrets.DOCKER_USERNAME }}/devsecure-api:latest
